### ISSUE TITLE
TMC HSR simulator gitlab not accessible

### ISSUE THREAD

**Issue by dlee640** [k1majd/CBF_TB_RRT#1]
Dear Keyvan Majd,

First off, I really enjoyed reading through your work on `Safe navigation in human occupied environments using sampling and CBFs`. I would like to simulate your code for the learning purposes.

I was able to set up everything else, but the link you posted for TMC HSR simlator: (https://docs.hsr.io/hsrb_user_manual_en/howto/pc_install.html) takes me to the gitlab signin page where I cannot log in. I have created a gitlab account (username: dlee640 / email: dlee640@gatech.edu) but it would not log in. Would you be able to grant access for me or provide a different link for HSR simulator installation guide?

Thank you for your time.

Sincerely,

Danny Lee

**Comment by k1majd** [comment]
Hello Danny, 

If you want to work with HSR model, you need to contact HSR support for access. You can find more info here: [https://docs.hsr.io/hsrb_user_manual_en/troubleshoot/troubleshoot.html](https://docs.hsr.io/hsrb_user_manual_en/troubleshoot/troubleshoot.html)

Instead, you can also use another differential mobile robot model in Gazebo such as Turtulebot3. 

Bests,
Keyvan

**Comment by dlee640** [comment]
Thank you for the prompt response Keyvan. Once again, the link you attached above shows nothing from my side, since I do not have affiliation with HSR. Therefore, I would have to stick to turtlebot (or other) robots. I can see that there are several launch files under the `cbf_ros` folder. Do you have a launch file that I can use instead of `demo.launch` & `Tjunction.launch` that doesn't use `hsrb_gazebo_launch` package? or would I have to modify those files myself for them to use turtlebot model and public map/world files?

**Comment by k1majd** [comment]
Unfortunately, we don't have a world launch file with Turtlebot config. We'll add it to our future updates.

**Comment by dlee640** [comment]
Thank you for your response.
